#include "holberton.h"
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
/**
 *
 */
int main()
{
	int len = 0, _len = 0;
	char *str = "hola";

	len = printf("%b\n", 98);
	_len = _printf("%b\n", 98);
	printf("------------\n");
	len = printf("%d\n", 6);
	_len = _printf("%d\n", 6);
	printf("------------\n");
	printf("%d\n", 1024);
	_printf("%d\n", 1024);
	printf("------------\n");
	printf("%d\n", -1024);
	_printf("%d\n", -1024);
	printf("------------\n");
	printf("%d\n", 0);
	_printf("%d\n", 0);
	printf("------------\n");
	printf("%d\n", INT_MAX);
	_printf("%d\n", INT_MAX);
	printf("------------\n");
	printf("%d\n", INT_MIN);
	_printf("%d\n", INT_MIN);
	printf("------------\n");
	printf("There is %d bytes in %d KB\n", 1024, 1);
	_printf("There is %d bytes in %d KB\n", 1024, 1);
	printf("------------\n");
	printf("%d - %d = %d\n", 1024, 2048, -1024);
	_printf("%d - %d = %d\n", 1024, 2048, -1024);
	printf("------------\n");
	printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	_printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("------------\n");
	printf("%i\n", 1024);
	_printf("%i\n", 1024);
	printf("------------\n");
	printf("%i\n", -1024);
	_printf("%i\n", -1024);
	printf("------------\n");
	printf("%i\n", 0);
	_printf("%i\n", 0);
	printf("------------\n");
	printf("%i\n", INT_MAX);
	_printf("%i\n", INT_MAX);
	printf("------------\n");
	printf("%i\n", INT_MIN);
	_printf("%i\n", INT_MIN);
	printf("------------\n");
	printf("There is %i bytes in %i KB\n", 1024, 1);
	_printf("There is %i bytes in %i KB\n", 1024, 1);
	printf("------------\n");
	printf("%i - %i = %i\n", 1024, 2048, -1024);
	_printf("%i - %i = %i\n", 1024, 2048, -1024);
	printf("------------\n");
	printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	_printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
	printf("------------\n");
	printf("%d == %i\n", 1024, 1024);
	_printf("%d == %i\n", 1024, 1024);
	printf("------------\n");
	printf("iddi%diddiiddi\n", 1024);
	_printf("iddi%diddiiddi\n", 1024);
	printf("------------\n");
	printf("%d\n", 10000);
	_printf("%d\n", 10000);
	printf("------------\n");
	printf("%i\n", 10000);
	_printf("%i\n", 10000);
	printf("***************************************\n\n");
	printf("------------\n");
        printf("Let's print a simple sentence.\n");
	_printf("Let's print a simple sentence.\n");
	printf("------------\n");
	printf("%c", 'S');
	_printf("%c", 'S');
	printf("------------\n");
	printf("A char inside a sentence: %c. Did it work?\n", 'F');
	_printf("A char inside a sentence: %c. Did it work?\n", 'F');
	printf("------------\n");
	printf("Let'see if the cast is correctly done: %c. Did it work?\n", 48);
	_printf("Let'see if the cast is correctly done: %c. Did it work?\n", 48);
	printf("------------\n");
	printf("%s", "This sentence is retrieved from va_args!\n");
	_printf("%s", "This sentence is retrieved from va_args!\n");
	printf("------------\n");
	printf("Complete the sentence: You %s nothing, Jon Snow.\n", "know");
	_printf("Complete the sentence: You %s nothing, Jon Snow.\n", "know");
	printf("------------\n");
	printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
	_printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
	printf("------------\n");
	printf("%c%cth %s%s a%cg%s: Y%sou %s no%ching%s Snow.%c", 'W', 'i', "some ", "more", 'r', "s", "", "know", 't', ", Jon", '\n');
	_printf("%c%cth %s%s a%cg%s: Y%sou %s no%ching%s Snow.%c", 'W', 'i', "some ", "more", 'r', "s", "", "know", 't', ", Jon", '\n');
	printf("------------\n");
	printf("%%\n");
	_printf("%%\n");
	printf("------------\n");
	printf("Should print a single percent sign: %%\n");
	_printf("Should print a single percent sign: %%\n");
	printf("------------\n");
	printf("%s%c%c%c%s%%%s%c", "Loading ", '.', '.', '.', " 99", " Please wait", '\n');
	_printf("%s%c%c%c%s%%%s%c", "Loading ", '.', '.', '.', " 99", " Please wait", '\n');
	printf("------------\n");
	printf("css%ccs%scscscs\n", 'T', "Test");
	_printf("css%ccs%scscscs\n", 'T', "Test");
	printf("------------\n");
	printf(NULL);
	_printf(NULL);
	printf("------------\n");
	printf("%c", '\0');
	_printf("%c", '\0');
	printf("------------\n");
	printf("%\n");
	printf("%\n");
	printf("------------\n");
	printf("%!\n");
	_printf("%!\n");
	printf("------------\n");
	printf("%K\n");
	_printf("%K\n");
	printf("------------\n");
	printf("%s\n", str);
	_printf("%s\n", str);
	printf("LENGHT-> :%d _:%d %s\n", len, _len, str);
	return (0);
}
